# A Linter Workflow
# https://www.youtube.com/watch?v=mFFXuXjVgkU&ab_channel=DevOpsJourney
# https://github.com/devopsjourney1/mygitactions

# name: Super-Linter

# on: push

# jobs:
#   super-lint:
#     name: Lint code base
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Run Super-Linter
#         uses: github/super-linter@v4.9.2
#         env:
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
